window.APP_CONFIG = {
  supportedLangs: ['en', 'ru', 'sr'],
  footerLinks: {
    site: 'https://nikolaysemenov.ru',
    github: 'https://github.com/ksider/nikolaysemenov.ru/tree/main/ftir',
  },
  chart: {
    defaultXRange: { min: 500, max: 4000 },
    zones: [
      { label: 'X–H heteroatoms', start: 4000, end: 2500, color: '#fb923c' },
      { label: 'C–H', start: 3100, end: 2800, color: '#fde047', text: '#111827' },
      { label: 'C≡C / C≡N', start: 2300, end: 2100, color: '#86efac', text: '#065f46' },
      { label: 'C=O', start: 1850, end: 1650, color: '#fb923c' },
      { label: 'C=C', start: 1650, end: 1500, color: '#86efac', text: '#065f46' },
      { label: 'halogenated', start: 1400, end: 1000, color: '#86efac', text: '#065f46' },
      { label: 'ethers', start: 1300, end: 1100, color: '#38bdf8', text: '#0b213b' },
      { label: 'organometallic', start: 1100, end: 700, color: '#fde047', text: '#111827' },
    ],
  },
  translations: {
    en: {
      title: 'FTIR TXT → CSV',
      description: 'Select multiple .txt files (FTIR spectra), set file name, merge to CSV, save a copy, and view the chart.',
      filesLabel: 'Files (.txt):',
      sampleIndex: 'Sample index (optional):',
      fileName: 'Output file name (.csv):',
      mergeBtn: 'Merge',
      appendFiles: 'Add files',
      chartSettings: 'Chart settings',
      xRange: 'X range (reverse):',
      yRange: 'Y range:',
      offsetsLabel: 'Y offsets per curve:',
      refresh: 'Refresh chart',
      saveCsv: 'Save CSV',
      resetZoom: 'Reset zoom',
      baselineSection: 'Baseline fit',
      baselineSeriesLabel: 'Series',
      baselineDegree: 'Degree',
      baselinePreview: 'Preview',
      baselineApply: 'Apply',
      baselineRevert: 'Revert',
      peaksTitle: 'Peaks / stripes',
      addStripe: 'Add stripe',
      copyStripes: 'Copy table',
      exportSession: 'Export session',
      importSession: 'Import session',
      copyPng: 'Copy chart PNG',
      copySvg: 'Copy chart SVG',
      peaksEmpty: 'No stripes yet. Set a marker and add it here.',
      tipPlaceholder: 'Tip database: coming soon',
      colWave: 'Wavenumber',
      colLabel: 'Label',
      colTip: 'Tip',
      peakHint: 'Click the chart to place a marker, then add it here.',
      statusNoFiles: 'Add at least one file.',
      statusReading: 'Reading files...',
      statusSending: 'Merging...',
      statusReadyToSave: 'Merged. Use Save CSV to export visible series.',
      statusSaved: (p) => `Saved: ${p}`,
      statusNoDataCols: 'No data columns found (only wavenumber?)',
      statusNoNumeric: 'No numeric data to plot.',
      statusNoVisible: 'Select at least one series to save.',
      language: 'Language:',
      yAuto: 'auto',
    },
    ru: {
      title: 'FTIR TXT → CSV',
      description: 'Выберите несколько .txt файлов (спектры ФТИР), задайте имя, объедините, сохраните копию и смотрите график.',
      filesLabel: 'Файлы (.txt):',
      sampleIndex: 'Индекс образца (опционально):',
      fileName: 'Имя итогового файла (.csv):',
      mergeBtn: 'Объединить',
      appendFiles: 'Добавить файлы',
      chartSettings: 'Настройки диаграммы',
      xRange: 'Диапазон X (реверс):',
      yRange: 'Диапазон Y:',
      offsetsLabel: 'Смещения по Y для кривых:',
      refresh: 'Обновить график',
      saveCsv: 'Сохранить CSV',
      resetZoom: 'Сбросить зум',
      baselineSection: 'Базовая линия',
      baselineSeriesLabel: 'Серия',
      baselineDegree: 'Степень',
      baselinePreview: 'Предпросмотр',
      baselineApply: 'Применить',
      baselineRevert: 'Сбросить',
      peaksTitle: 'Пики / полосы',
      addStripe: 'Добавить полосу',
      copyStripes: 'Скопировать таблицу',
      exportSession: 'Экспорт сессии',
      importSession: 'Импорт сессии',
      copyPng: 'Скопировать PNG',
      copySvg: 'Скопировать SVG',
      peaksEmpty: 'Пока нет полос. Поставьте маркер и добавьте его сюда.',
      tipPlaceholder: 'Подсказки из базы появятся здесь',
      colWave: 'Волновое число',
      colLabel: 'Метка',
      colTip: 'Подсказка',
      peakHint: 'Кликните по графику, чтобы поставить маркер, затем добавьте его сюда.',
      statusNoFiles: 'Добавьте хотя бы один файл.',
      statusReading: 'Чтение файлов...',
      statusSending: 'Объединение...',
      statusReadyToSave: 'Объединено. Нажмите «Сохранить CSV» для видимых кривых.',
      statusSaved: (p) => `Сохранено: ${p}`,
      statusNoDataCols: 'Не удалось найти столбцы данных (только wavenumber?)',
      statusNoNumeric: 'Нет числовых данных для построения графика.',
      statusNoVisible: 'Отметьте хотя бы одну кривую для сохранения.',
      language: 'Язык:',
      yAuto: 'auto',
    },
    sr: {
      title: 'FTIR TXT → CSV',
      description: 'Izaberite više .txt fajlova (FTIR spektri), unesite ime, spojite u CSV, sačuvajte kopiju i pogledajte graf.',
      filesLabel: 'Fajlovi (.txt):',
      sampleIndex: 'Indeks uzorka (opciono):',
      fileName: 'Naziv izlaznog fajla (.csv):',
      mergeBtn: 'Spoji',
      appendFiles: 'Dodaj fajlove',
      chartSettings: 'Podešavanja grafa',
      xRange: 'Opseg X (obrnuto):',
      yRange: 'Opseg Y:',
      offsetsLabel: 'Pomeraj po Y za krive:',
      refresh: 'Osveži graf',
      saveCsv: 'Sačuvaj CSV',
      resetZoom: 'Resetuj zum',
      baselineSection: 'Baseline fit',
      baselineSeriesLabel: 'Serija',
      baselineDegree: 'Stepen',
      baselinePreview: 'Pregled',
      baselineApply: 'Primeni',
      baselineRevert: 'Poništi',
      peaksTitle: 'Vrhovi / trake',
      addStripe: 'Dodaj traku',
      copyStripes: 'Kopiraj tabelu',
      exportSession: 'Izvezi sesiju',
      importSession: 'Uvezi sesiju',
      copyPng: 'Kopiraj PNG',
      copySvg: 'Kopiraj SVG',
      peaksEmpty: 'Još nema traka. Postavi marker i dodaj ga ovde.',
      tipPlaceholder: 'Saveti iz baze uskoro',
      colWave: 'Talasni broj',
      colLabel: 'Oznaka',
      colTip: 'Savet',
      peakHint: 'Klik na graf postavlja marker, pa ga dodaj ovde.',
      statusNoFiles: 'Dodajte bar jedan fajl.',
      statusReading: 'Čitanje fajlova...',
      statusSending: 'Spajanje...',
      statusReadyToSave: 'Spojeno. Klikni „Sačuvaj CSV” za vidljive krive.',
      statusSaved: (p) => `Sačuvano: ${p}`,
      statusNoDataCols: 'Nema kolona sa podacima (samo wavenumber?)',
      statusNoNumeric: 'Nema numeričkih podataka za graf.',
      statusNoVisible: 'Izaberi bar jednu krivu za čuvanje.',
      language: 'Jezik:',
      yAuto: 'auto',
    },
  },
};
