// Texts and defaults for the client-only version.
window.APP_CONFIG = {
  defaultLang: 'ru',
  translations: {
    ru: {
      title: 'PDF из картинок с сортировкой',
      subtitle: 'Загрузите изображения, перетаскивайте в нужном порядке и сохраняйте в PDF одним кликом.',
      addImages: 'Добавить изображения',
      sortLabel: 'Сортировка',
      sortManual: 'Ручной порядок',
      sortNameAsc: 'Имя A → Я',
      sortNameDesc: 'Имя Я → A',
      sortTimeAsc: 'Старые → новые',
      sortTimeDesc: 'Новые → старые',
      clear: 'Очистить',
      save: 'Сохранить как PDF',
      empty: 'Перетащите файлы или нажмите «Добавить изображения».',
      hint: 'Поддерживается drag-n-drop: захватите карточку и переместите её.',
      drag: 'Перетащить',
      remove: 'Удалить',
      confirm: 'Скачать файл «{name}»?',
      fileNameTitle: 'Имя PDF файла',
      fileNameAria: 'Имя PDF',
      statusReady: 'Готово',
      statusError: 'Ошибка: {msg}',
      statusUploading: 'Готовим файлы…',
      statusMerging: 'Собираем PDF…',
      statusDownloading: 'Скачиваем…',
      typeImage: 'Изображение',
      typePdf: 'PDF',
      typeDocx: 'Word',
      convertingDocx: '{name}: конвертирую Word…',
      pdfLocked: 'Файл «{name}» защищен, пропускаю.'
    },
    en: {
      title: 'Image to PDF with Sorting',
      subtitle: 'Upload images, drag to reorder, and save to PDF in one click.',
      addImages: 'Add images',
      sortLabel: 'Sorting',
      sortManual: 'Manual order',
      sortNameAsc: 'Name A → Z',
      sortNameDesc: 'Name Z → A',
      sortTimeAsc: 'Older → newer',
      sortTimeDesc: 'Newer → older',
      clear: 'Clear',
      save: 'Save as PDF',
      empty: 'Drag files here or click “Add images”.',
      hint: 'Drag-n-drop supported: grab a card and move it.',
      drag: 'Drag',
      remove: 'Remove',
      confirm: 'Download file “{name}”?',
      fileNameTitle: 'PDF file name',
      fileNameAria: 'PDF name',
      statusReady: 'Ready',
      statusError: 'Error: {msg}',
      statusUploading: 'Preparing files…',
      statusMerging: 'Building PDF…',
      statusDownloading: 'Downloading…',
      typeImage: 'Image',
      typePdf: 'PDF',
      typeDocx: 'Word',
      convertingDocx: '{name}: converting Word…',
      pdfLocked: 'File “{name}” is protected, skipping.'
    },
    sr: {
      title: 'PDF od slika sa sortiranjem',
      subtitle: 'Otpremite slike, prevucite za redosled i sačuvajte kao PDF jednim klikom.',
      addImages: 'Dodaj slike',
      sortLabel: 'Sortiranje',
      sortManual: 'Ručno',
      sortNameAsc: 'Ime A → Š',
      sortNameDesc: 'Ime Š → A',
      sortTimeAsc: 'Starije → novije',
      sortTimeDesc: 'Novije → starije',
      clear: 'Očisti',
      save: 'Sačuvaj kao PDF',
      empty: 'Prevucite fajlove ovde ili kliknite „Dodaj slike”.',
      hint: 'Podržan je drag-n-drop: uhvatite karticu i pomerite je.',
      drag: 'Prevuci',
      remove: 'Ukloni',
      confirm: 'Preuzeti fajl „{name}”?',
      fileNameTitle: 'Naziv PDF fajla',
      fileNameAria: 'Naziv PDF-a',
      statusReady: 'Spremno',
      statusError: 'Greška: {msg}',
      statusUploading: 'Pripremam fajlove…',
      statusMerging: 'Pravim PDF…',
      statusDownloading: 'Preuzimam…',
      typeImage: 'Slika',
      typePdf: 'PDF',
      typeDocx: 'Word',
      convertingDocx: '{name}: konvertujem Word…',
      pdfLocked: 'Fajl „{name}” je zaštićen, preskačem.'
    }
  }
};
